language: go
go: 
- 1.15.x

env: GO111MODULE=on

before_install: cd app

script:
- go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)