// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeRateLimiterMiddleware() (*RateLimiterMiddleware, error) {
	config, err := NewConfig()
	if err != nil {
		return nil, err
	}
	limiterRepository, err := NewRedisLimiterRepository(config)
	if err != nil {
		return nil, err
	}
	rateLimiterMiddleware := NewRateLimiterMiddleware(config, limiterRepository)
	return rateLimiterMiddleware, nil
}

func InitializeServer(ginMiddlewareCollection *GinMiddlewareCollection) (*Server, error) {
	config, err := NewConfig()
	if err != nil {
		return nil, err
	}
	engine := NewEngine(config, ginMiddlewareCollection)
	server := NewServer(config, engine)
	return server, nil
}
