// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	config, err := NewConfig()
	if err != nil {
		return nil, err
	}
	limiterRepository, err := NewRedisLimiterRepository(config)
	if err != nil {
		return nil, err
	}
	rateLimiterMiddleware := NewRateLimiterMiddleware(config, limiterRepository)
	engine := NewEngine(config, rateLimiterMiddleware)
	server := NewServer(config, engine)
	return server, nil
}
